EmployeeManagementSystem/Controllers/homeController.cs
using EmployeeManagementSystem.Models;
using EmployeeManagementSystem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagementSystem.Controllers
{
    [Authorize]
    [Route("[Controller]/[action]")]
    [Route("[Controller]")]
    public class homeController:Controller
    {
        private readonly IEmployeeRepository _repos;
        private readonly IHostingEnvironment env;
        private readonly ILogger<homeController> logger;

        public homeController(IEmployeeRepository repos, IHostingEnvironment env, ILogger<homeController> logger)
        {
            _repos = repos;
            this.env = env;
            this.logger = logger;
        }
        [AllowAnonymous]
        [Route("")]
        [Route("~/")]
       
        public ViewResult index()
        {
          return  View(_repos.getAllEmployees());
        }
        [AllowAnonymous]
        [Route("{id?}")]
        public ViewResult Details(int ? id)
        {
            logger.LogTrace("Log Trace");
            logger.LogDebug("Log Debug");
            logger.LogInformation("Log Information");
            logger.LogWarning("Log Warning");
            logger.LogError("Log Error");
            logger.LogCritical("Log Critical");

            //Cheking the employee id for Not availabe id

            Employee emp = _repos.getEmployee(id.Value);
            //Will throw Excption press continue to see the exception Handled
           // throw new Exception("Iam thrown from Details");
            if (emp==null)
            {
                Response.StatusCode = 404;
                return View("EmplooyeeNotFound", id.Value);
            }
            HomeDetailsViewModel hdvm = new HomeDetailsViewModel()
            {
                employee = emp,

                PageTitle = "Employee Details"
            };


            return View(hdvm);
        }
        [HttpGet]
       
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
       
        public IActionResult Create(EmpoloyeeCreateViewModel model)
        {
            string uniqueFileName= processUpLoadedFile(model); ;
         
            if (ModelState.IsValid)
            {
                //We need to Create Employee Object Out of model
                Employee newEmployee = new Employee()
                {
                    Name = model.Name,
                    Email = model.Email,
                    Department = model.Department,
                    Photopath = uniqueFileName

                };
                 _repos.Add(newEmployee);
                //Change the Create and Details View for handling photos remove noimage.jpgthere
                return RedirectToAction("details", new { id = newEmployee.Id });
            }
            else
            {
                return View();
            }
            
        }

        [HttpGet]
        
        public ViewResult Edit(int id)
        {
            
           
            Employee employee = _repos.getEmployee(id);
            EmployeeEditViewModel employeeEditViewModel = new EmployeeEditViewModel()
            {
                Id = employee.Id,
                Name = employee.Name,
                Email= employee.Email,
                Department=employee.Department,
                ExistingPhotoPath=employee.Photopath

            };
            return View(employeeEditViewModel);
        }
        [HttpPost]
        
        public IActionResult Edit(EmployeeEditViewModel model)

        {
            Employee upDateEmployee = _repos.getEmployee(model.Id);
            upDateEmployee.Name = model.Name;
            upDateEmployee.Email = model.Email;
            upDateEmployee.Department = model.Department;
            //Checking for photo property not eqal to null for determining changes made to Photos
            if (model.Photo != null)
            {
                if (model.ExistingPhotoPath != null)
                {
                    string filePath = Path.Combine(env.WebRootPath, "images", model.ExistingPhotoPath);
                    System.IO.File.Delete(filePath);
                }
                //Updating Photos of Updated Photos if photos changes
                upDateEmployee.Photopath = processUpLoadedFile(model);
            }


            if (ModelState.IsValid)
            {


                _repos.Update(upDateEmployee);

                return RedirectToAction("index");
            }
            else
            {
                return View();
            }

        }


        //Created a seprate method for Handlig photo file upload used Interface for  EmpoloyeeCreateViewModel
        //as the parent iNterface  so both EmpoloyeeCreateViewModel and EmployeeEditViewModel use the same method
        private string processUpLoadedFile(EmpoloyeeCreateViewModel model)
        {
            string uniqueFileName = null;
            if (model.Photo != null)
            {
                ///To get the Phyiscal Path of the root folder we use IConfiguration 
                /// need to inject IConfiguration here acessroot folder

                string upLoadsFolder = Path.Combine(env.WebRootPath, "images");
                //We want the file Name to be Unique  so we use GUID class
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                //lets combine upLoadsFolder and  uniqueFileName
                string filePath = Path.Combine(upLoadsFolder, uniqueFileName);
                //Added Usinf since the Filestream to be closed afetr Uploading fle
                using(var fileStream=new FileStream(filePath, FileMode.Create))
                {
                    model.Photo.CopyTo(fileStream);
                }
                

            }

            return uniqueFileName;
        }
    }
}

EmployeeManagementSystem/Views/Home/EmplooyeeNotFound.cshtml
@model int;
@{
    ViewBag.Title = "404 Error";
}
<div class="alert alert-danger mt-1 mb-1">
    <h4>404 Page Not Found</h4>
    <hr />
    <h5>
        Employee with ID = @Model cannot be found
    </h5>
</div>
<a asp-action="Index" asp-controller="Home" class="btn btn-outline-success" style="width:auto">
    Click Here to See The List Of All Employees

</a>

EmployeeManagementSystem/Views/Home/Index.cshtml
 @model IEnumerable<EmployeeManagementSystem.Models.Employee>
@{ 
   
    ViewBag.Title = "Employees List";
    

}

    
    <div class="card-deck">
        @foreach (var employee in Model)
        {
           var photopath = "~/images/" +( employee.Photopath ?? "noimage.jpg");
            <div class="card m-3" style="min-width:18rem; max-width:30.5%">
                <div class="card-header">
                    <h3>@employee.Name</h3>
                </div>

                <img class="card-img-top imageThumbnail" src=@photopath asp-append-version="true"/>
                <div class="card-footer text-center">
                   
                   
                   <a asp-controller="home" asp-action="details" asp-route-Id="@employee.Id" class="btn btn-primary m-1">View</a>
                   
                    <a asp-controller="home" asp-action="edit" asp-route-id="@employee.Id" class="btn btn-primary  m-1">Edit</a>
                    <a href="#" class="btn btn-danger  m-1">Delete</a>

                </div>
            </div>
        }

    </div>
   

EmployeeManagementSystem/Views/Home/create.cshtml
@model EmpoloyeeCreateViewModel
@{
    ViewBag.Title = "Create Employee";
    
   
}

    <form enctype="multipart/form-data" class="mt-3" asp-controller="Home" asp-action="Create" method="post">
        <div class="form-group row">
            <label class="col-sm-2 col-form-label" asp-for="Name"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" placeholder="Name" />
                <span asp-validation-for="Name" class="text-danger"></span>

            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label" asp-for="Email"></label>
            <div class="col-sm-10">
                <input asp-for="Email" class="form-control" placeholder="Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label" asp-for="Department"></label>
            <div class="col-sm-10">
                <select class="custom-select mr-sm-2" asp-for="Department" asp-items="Html.GetEnumSelectList<Dept>()">
                    <option value="">Select A Value</option>

                </select>
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label" asp-for="Photo"></label>
            <div class="col-sm-10">
                <div class="custom-file">
                    <input multiple asp-for="Photo" class="form-control  custom-file-input" />
                    <label class="custom-file-label">Choose File .........</label>
                </div>
            </div>
        </div>


        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-sm-10">

                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>

        @section  scripts{
                <script>
                    //Code for  Handling Multiple files
                    //$(document).ready(function () {
                    //    $('.custom-file-input').on("change", function () {
                    //        var fileName = $(this).next('.custom-file-label');
                    //        var files = $(this)[0].files;
                    //        if (files.length > 1) {
                    //            fileLabel.html(files.length + ' files selected');
                    //        } else if (files.length == 1) {
                    //            fileLabel.html(files[0].name);
                    //        }
                    //    });

                    //});

                        $(document).ready(function () {
                            $('.custom-file-input').on("change", function () {
                                // var fileName = $(this).val().split("\\").pop();
                                // $(this).next('.custom-file-label').html(fileName);
                                var fileLabel = $(this).next('.custom-file-label');
                                var files = $(this)[0].files;
                                if (files.length > 1) {
                                    fileLabel.html(files.length + 'files selected');
                                } else if (files.length == 1) {
                                    fileLabel.html(files[0].name);
                                }
                            });
                    });
                
            </script>

        }

    </form>

EmployeeManagementSystem/Views/Home/details.cshtml
@model EmployeeManagementSystem.ViewModels.HomeDetailsViewModel

@{

    ViewBag.Title = "Employees Details";
    var photopath = "~/images/" +( Model.employee.Photopath ?? "noimage.jpg");

}
<div class="row justify-content-center m-3">
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <h1>@Model.employee.Name</h1>
            </div>
            <div class="card-body text-center">
                <img class="card-img-top" src=@photopath  asp-append-version="true"/>
                <h4> Employee ID:@Model.employee.Id </h4>
                <h4> Email:@Model.employee.Email </h4>
                <h4> Department:@Model.employee.Department </h4>

            </div>
            <div class="card-footer text-center">
                <a asp-controller="home" asp-action="index"  class="btn btn-primary">Back</a>
                <a  asp-controller="home" asp-action="edit" asp-route-id="@Model.employee.Id"  class="btn btn-primary">Edit</a>
                <a href="#" class="btn btn-danger">Delete</a>

            </div>
        </div>
    </div>

</div>

@section scripts{
    <script src="~/js/CustomScript.js"></script>
}

EmployeeManagementSystem/Views/Home/edit.cshtml
@model EmployeeEditViewModel;
@{ 
    ViewBag.Title = "Edit " + Model.Name;
    var photopath = "~/images/" +( Model.ExistingPhotoPath ?? "noimage.jpg");
}
    <form enctype="multipart/form-data" class="mt-3" asp-controller="home" asp-action="edit" method="post">
        <input hidden asp-for="Id" />
        <input hidden asp-for="ExistingPhotoPath" />
        <div class="form-group row">
            <label class="col-sm-2 col-form-label" asp-for="Name"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" placeholder="Name" />
                <span asp-validation-for="Name" class="text-danger"></span>

            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label" asp-for="Email"></label>
            <div class="col-sm-10">
                <input asp-for="Email" class="form-control" placeholder="Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label" asp-for="Department"></label>
            <div class="col-sm-10">
                <select class="custom-select mr-sm-2" asp-for="Department" asp-items="Html.GetEnumSelectList<Dept>()">
                    <option value="">Select A Value</option>

                </select>
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label" asp-for="Photo"></label>
            <div class="col-sm-10">
                <div class="custom-file">
                    <input multiple asp-for="Photo" class="form-control  custom-file-input" />
                    <label class="custom-file-label">Click Here To Chnage Photo</label>
                </div>
            </div>
        </div>
        <div class="form-group row col-sm-4 offset-4" >
            <img src=@photopath class="imageThumbnail" asp-append-version="true" />
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Update</button>
                <a asp-controller="home" asp-action="index" class="btn btn-primary">Cancel</a>
            </div>
        </div>

        @section scripts{
            <script>
                    //Code for  Handling Multiple files
                    //$(document).ready(function () {
                    //    $('.custom-file-input').on("change", function () {
                    //        var fileName = $(this).next('.custom-file-label');
                    //        var files = $(this)[0].files;
                    //        if (files.length > 1) {
                    //            fileLabel.html(files.length + ' files selected');
                    //        } else if (files.length == 1) {
                    //            fileLabel.html(files[0].name);
                    //        }
                    //    });

                    //});

                        $(document).ready(function () {
                            $('.custom-file-input').on("change", function () {
                                // var fileName = $(this).val().split("\\").pop();
                                // $(this).next('.custom-file-label').html(fileName);
                                var fileLabel = $(this).next('.custom-file-label');
                                var files = $(this)[0].files;
                                if (files.length > 1) {
                                    fileLabel.html(files.length + 'files selected');
                                } else if (files.length == 1) {
                                    fileLabel.html(files[0].name);
                                }
                            });
                    });

            </script>
        }
     </form>